import TRANSPARENT_IMAGES from '@/generated/image-transparency.json'

/**
 * Does this image have enough real transparency that a loading shimmer BEHIND it would show
 * straight through?
 *
 * The shimmer is deliberately placed behind the image rather than fading out on top of it, which
 * only works because an opaque image covers it as it decodes. An image with real transparency
 * breaks that: you see the shimmer AND the picture at the same time, and it reads as a shimmer
 * that refuses to go away (the /writing/on-the-design-of-dot hero is 11% transparent).
 *
 * The map is generated by scripts/extract-image-transparency.mjs, which measures the actual
 * transparent fraction and lists only the images over its threshold. Baked bezel screenshots
 * carry an alpha channel too, but only for their rounded corners (~0% of the area), so they
 * stay below the threshold and keep their shimmer.
 */
export function bleedsShimmer(src?: string): boolean {
  if (!src) return false
  return (TRANSPARENT_IMAGES as Record<string, boolean>)[src] === true
}
